name: Run tests

on:
  pull_request:
    paths:
      - 'cs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Test
        run: LANGUAGE=cs go test -v ./... -count 1
